---
- name: Verify
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Try to use cntlm
      ansible.builtin.shell:
        cmd: echo "some_string" | cntlm -H
      changed_when: false
